feat(tools): error out on missing arguments

diff --git a/tools/run b/tools/run
--- a/tools/run
+++ b/tools/run
@@ -153,6 +153,11 @@ ts() {
 }
 
 init() {
+    if [ $# -eq 0 ]; then
+        printf "Error: No arguments.\n"
+        exit 1
+    fi
+
     # Go to project's root directory.
     cd "$(git rev-parse --show-toplevel)" || exit
 }
