refactor(tools): add variadic arguments in check

diff --git a/tools/run b/tools/run
--- a/tools/run
+++ b/tools/run
@@ -3,8 +3,7 @@
 log() { printf "%s %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$@"; }
 
 check() {
-    if ! command -v "$1" >/dev/null; then
-        printf "Error: Missing '%s' dependency.\n" "$1"
+    hint() {
         case "$1" in
             air) printf "Install it with 'go install github.com/cosmtrek/air@latest'.\n" ;;
             curl) printf "Install 'curl' with your package manager.\n" ;;
@@ -14,8 +13,15 @@ check() {
             unzip) printf "Install 'unzip' with your package manager.\n" ;;
             inotify*) printf "Install 'notify-tools' with your package manager.\n" ;;
         esac
-        exit 1
-    fi
+    }
+
+    for arg in "$@"; do
+        if ! command -v "$arg" >/dev/null; then
+            printf "Error: Missing '%s' dependency.\n" "$arg"
+            hint "$arg"
+            exit 1
+        fi
+    done
 }
 
 export_secrets() {
@@ -28,8 +34,7 @@ export_secrets() {
 
 fonts() {
     log "Downloading fonts."
-    check curl
-    check unzip
+    check curl unzip
 
     # Extract the latest release.
     src="$(curl -s https://api.github.com/repos/rsms/inter/releases/latest | sed -n 's/.*browser_download_url.*"\(http.*\)"/\1/p')"
@@ -84,8 +89,7 @@ prod() {
 
 sass() {
     log "Compiling SCSS files."
-    check sassc
-    check inotifywait
+    check sassc inotifywait
 
     # Sassc fails if directory doesn't exist.
     mkdir -p web/static/css
@@ -153,9 +157,8 @@ init() {
         exit 1
     fi
 
-    check git # Seems unnecessary, but you never know.
-    check go
-    check air
+    # Seems unnecessary, but you never know.
+    check git go air
 
     # Go to project's root directory.
     cd "$(git rev-parse --show-toplevel)" || exit
